#server
server:
  port: 9103
  error:
    include-exception: true
  servlet:
    encoding:
      charset: UTF-8
      enabled: true


#spring
spring:
  #datasource
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    #url: jdbc:log4jdbc:oracle:thin:@//seoulit702.iptime.org:1524/xe
    url: jdbc:log4jdbc:oracle:thin:@//localhost:1521/xe
    username: acc752
    password: acc752
  #main
  main:
    allow-bean-definition-overriding: true
  #Google SendMail
  mail:
    host: smtp.gmail.com
    port: 587
    username: seoulit50@gmail.com
    password: '!admin8282'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #FileUpload (FileSizeLimitExceed)
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 50MB
      max-request-size: 50MB

#mybatis
mybatis:
  mapper-locations: classpath:/mapper/**/*SqlMap.xml
  type-aliases-package: kr.co.seoulit.account
  configuration:
    jdbc-type-for-null: null
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true

#logging
logging:
  level:
    com:
      azurealstn:
        codespringweb:
          mapper: debug
    root: info

#swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    tagsSorter: alpha
    operations-sorter: alpha
    display-request-duration: true





